be robust to cmd being called pytest-3 or just pytest

diff --git a/src/wetsuite/do-tests b/src/wetsuite/do-tests
--- a/src/wetsuite/do-tests
+++ b/src/wetsuite/do-tests
@@ -1,7 +1,24 @@
-
+#!/bin/bash
 # Do tests.   Also calculate amount of test coverage, and wrangle that percentage into a file.
 
-pytest-3 --cov=wetsuite | tee >(cat >&2) | grep TOTAL | tr -s ' ' ' ' | cut -d ' ' -f 4   > coverage.txt
+# pytest-3 might be called pytest
+command_exists () {
+    type "$1" &> /dev/null ;
+}
+
+if command_exists pytest-3 ; then
+  TESTCMD="pytest-3"
+else
+  if command_exists pytest ; then
+    TESTCMD="pytest"
+  else
+     echo 'ERROR: could not find pytest.' >&2
+     exit 1
+  fi
+fi
+
+
+$TESTCMD --cov=wetsuite --cov-report html:coverage-report tests/ | tee >(cat >&2) | grep TOTAL | tr -s ' ' ' ' | cut -d ' ' -f 4   > coverage.txt
 # --cov-report html:coverage-report tests/
 
 
